sudo: required
language: bash

before_install:
    - git clone https://github.com/bats-core/bats-core.git
    - sudo ./bats-core/install.sh /usr/local
script:
    - ls -la
    - bats tests/check-quality-gate-test.bats
