sudo: required
language: bash
before_install:
    - git clone https://github.com/bats-core/bats-core.git
    - cd bats-core
    - ./install.sh /usr/local
script:
    - bats tests/check-quality-gate-test.bats
